[package]
name = "rust-terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29"
ratatui = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
notify = "8.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
